USE [easycollector]
GO

/****** Object:  View [dbo].[vw_FATDIVIDA]    Script Date: 22/03/2024 17:53:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vw_FATDIVIDA] AS

SELECT	A.ID_CLIENTE, 
		A.ID_CONTRATO, C.ID_CEDENTE, 
		A.ID_PRODUTO,
		B.ID_DIVIDA,
		B.DT_VENCIMENTO,
		B.VL_DIVIDA,
		A.NU_PLANO,
		B.NU_PRESTACAO,
		A.DT_CADASTRO, 
		A.DT_ATUALIZACAO, 
		A.DT_EXPIRACAO
FROM TB_CONTRATO A
INNER JOIN TB_DIVIDA B
ON A.ID_CONTRATO = B.ID_CONTRATO
INNER JOIN TB_CLIENTE C 
ON A.ID_CLIENTE = C.ID_CLIENTE
GO

