USE [easycollector]
GO

/****** Object:  View [dbo].[vw_META]    Script Date: 22/03/2024 17:53:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[vw_META] AS

SELECT  A.ID_META,
		A.ID_CEDENTE,
		MAX(C.ID_EQUIPE) AS ID_EQUIPE,
		A.NM_META,
		B.VL_META AS [META MENSAL]
FROM TB_META_INTERNA A
LEFT JOIN TB_META_INTERNA_COMISSAO B
on A.ID_META = B.ID_META
LEFT JOIN TB_META_INTERNA_EQUIPE C
on A.ID_META = C.ID_META
GROUP BY A.ID_META, A.ID_CEDENTE, A.NM_META, A.NU_DIA_PERIODO, B.VL_META
GO

