USE [easycollector]
GO

/****** Object:  View [dbo].[vw_ASSESSORIAS]    Script Date: 22/03/2024 17:50:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[vw_ASSESSORIAS] AS

SELECT  A.ID_ASSESSORIA AS [ID ASSESSORIA],
        A.NM_ASSESSORIA AS [NOME ASSESSORIA],
        A.NM_ENDERECO AS [ENDERECO],
        A.NM_NUMERO AS [NUMERO],
        A.NM_BAIRRO AS [BAIRRO],
        A.NM_CIDADE AS [CIDADE],
        A.NM_UF AS [UF],
        A.NU_CEP AS [CEP],
        A.NM_SITE AS [SITE],
        B.NU_DDD AS [DDD],
        B.NU_TELEFONE AS [TELEFONE],
        B.NU_RAMAL AS [RAMAL],
        B.NM_CONTATO AS [CONTATO],
        B.NM_EMAIL AS [E-MAIL],
        B.NM_CARGO AS [CARGO]
FROM TB_ASSESSORIA A
JOIN TB_ASSESSORIA_CONTATO B ON A.ID_ASSESSORIA = B.ID_ASSESSORIA
GO


